export enum AdministrationRoutes {
    ORAL = 'ORAL',
    INTRAMUSCULAR = 'INTRAMUSCULAR',
    INTRAVENOUS = 'INTRAVENOUS',
    SUBCUTANEOUS = 'SUBCUTANEOUS',
    INHALATION = 'INHALATION',
    TRANSDERMAL = 'TRANSDERMAL',
    NASAL = 'NASAL',
    OPHTHALMIC = 'OPHTHALMIC',
    OPTICS = 'OPTICS',
    TOPICAL = 'TOPICAL',
    RECTAL = 'RECTAL',
    VAGINAL = 'VAGINAL',
}
